### ISSUE TITLE
Upgrading to 8.0 from 7.6 fails - Table 'opensis.app' doesn't exist error at 2

### ISSUE THREAD

**Issue by eivindga** [OS4ED/openSIS-Classic#174]
When upgrading from 7.6 to 8, an error is displayed. See attached screenshot

![image](https://user-images.githubusercontent.com/2804405/129722079-397bca53-671c-4506-9d11-5b5e8aa6af81.png)

**Comment by openSISAdmin** [comment]
Please use the updated code from the repo and try again. We have added a fix. Let us know how it goes.

Thanks.

**Comment by sarika0lal** [comment]
Hello,

Apologies for the inconvenience caused.
We have updated our code. So, please use our latest code from the repository. We hope you won't have to face the issue again.

Thank you.

**Comment by fcortesjp** [comment]
whatever is on 8.0 available in github does not resolve this issue (I'm upgrading fro 7.4 to 8 and I also get this error)
